/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263hw01;

import org.apache.commons.cli.*;

public class App {
    public static void batch(String fileName){
        System.out.println(fileName);
    }

    public static void helpMessage(){
        System.out.println("usage: eval [OPTIONS] \n" +
                "Evaluation of simple mathematical expressions\n" +
                "-b,--batch <file>    batch file containing expressions to evaluate\n" +
                "-h,--help            print usage message\n" +
                "-o,--output <file>   output file\n" +
                "Copyright (C) 2021 Isaac D. Griffith");
        return ;
    }

    public static void output(String fileName){
        System.out.println(fileName);
    }

    public static void main(String[] args) throws ParseException {
        //***Definition Stage***
        // create Options object
        Options options = new Options();

        // add option "-b/--batch"
        options.addOption("b", "batch", true, "batch file containing expressions to evaluate");
        // add option "-h/--help"
        options.addOption("h", "help", false, "print usage message");
        // add option "-o/--output"
        options.addOption("o", "output", true, "output file");

        //***Parsing Stage***
        //Create a parser
        CommandLineParser parser = new DefaultParser();

        //parse the options passed as command line arguments
        CommandLine cmd = parser.parse( options, args);

        //***Interrogation Stage***
        //hasOptions checks if option is present or not
        if(cmd.hasOption("b") || cmd.hasOption("batch")){
            batch(cmd.getOptionValue("b"));
        }
        else if(cmd.hasOption("h") || cmd.hasOption("help")){
            helpMessage();
        }
        else if(cmd.hasOption("o") || cmd.hasOption("output")){
            output(cmd.getOptionValue("o"));
        }

    }
}